version: '3.4'

volumes:
    prometheus_data:
    grafana_data:
    certs:
    conf:
    vhost:
    dhparam:
    nginx-html:
    nginx-vhost:
    nginx-conf:

networks:
  default:
    external:
      name: nginx-proxy

services:
  grafana:
    image: grafana/grafana:7.3.7
    container_name: grafana_container
    depends_on:
      - prometheus
    user: "$UID:$GID"
    expose:
      - "3000"

    volumes:
      - ./grafana_data:/var/lib/grafana:rw
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - VIRTUAL_HOST=grafana.ubuntunet.net
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=grafana.ubuntunet.net
      - LETSENCRYPT_EMAIL=devops@ubuntunet.net
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.7.1
    container_name: prometheus_container
    volumes:
      - ./prometheus:/etc/prometheus:rw
      - prometheus_data:/prometheus:rw
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    expose: 
      - "9090"
    links:
      - cadvisor:cadvisor
      - alertmanager:alertmanager
    depends_on:
      - cadvisor
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=prometheus.ubuntunet.net
      - VIRTUAL_PORT=9090
      - LETSENCRYPT_HOST=prometheus.ubuntunet.net
      - LETSENCRYPT_EMAIL=devops@ubuntunet.net

  node-exporter:
    image: prom/node-exporter:v0.17.0
    container_name: node-exporter_container
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    expose:
      - "9100"

    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:v0.22.0
    container_name: alertmanager_container
    expose:
      - "9093"
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - default
    restart: unless-stopped
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=https://alertmanager.ubuntunet.net/'
    environment:
      - VIRTUAL_HOST=alertmanager.ubuntunet.net
      - VIRTUAL_PORT=9093
      - LETSENCRYPT_HOST=alertmanager.ubuntunet.net
      - LETSENCRYPT_EMAIL=devops@ubuntunet.net

  cadvisor:
    image: google/cadvisor:v0.32.0
    container_name: cadvisor_container
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 129.232.230.131:8081:8080

    restart: unless-stopped
