version: '3.4'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy:0.9
    restart: unless-stopped
    ports:
      - "196.32.212.219:80:80"
      - "196.32.212.219:443:443"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./htpasswd:/etc/nginx/htpasswd
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    restart: unless-stopped
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - ./htpasswd:/etc/nginx/htpasswd
      - nginx-conf:/etc/nginx/conf.d
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  nginx-conf:
  nginx-vhost:
  nginx-html:

networks:
  default:
    external:
      name: nginx-proxy
