development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV['ACTION_CABLE_BACKEND_URL'] %>
  # url: redis://localhost:6379/1
  # channel_prefix: switchboard_production
