# slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
    - send_resolved: true
      username: 'testbot'
      channel: '#devops'
      api_url: 'https://hooks.slack.com/services/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'
